package:
  name: zeromq
  version: 4.2.0

source:
  git_url: https://github.com/zeromq/libzmq.git
#  git_rev: master
#  fn: zeromq-4.0.5.tar.gz
#  url: http://download.zeromq.org/zeromq-4.0.5.tar.gz
#  sha1: a664ec63661a848ef46114029156a0a6006feecd
  #patches:
  #  - pedantic.patch [not win]

build:
  number: 1

requirements:
  build:
    - autoconf [not win]
    - automake [not win]
    - pkg-config [not win]
    - libtool [not win]
    - libsodium [not win]

  run:
    - libsodium [not win]

about:
  home: http://zeromq.org
  license: LGPL
