sudo: required

services:
    - docker

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      env: CONDA_PY=2.7
    - os: linux
      dist: trusty
      env: CONDA_PY=3.5
    - os: osx
      env: CONDA_PY=2.7
    - os: osx
      env: CONDA_PY=3.5

install:
  # Expand CONDA_CMD and ANACONDA_CMD alias
  - shopt -s expand_aliases
  # Set the anaconda environment
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "$CONDA_PY" == "2.7" ]]; then
        curl https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh;
      else
        curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
      fi;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      alias CONDA_CMD=conda;
      alias ANACONDA_CMD=anaconda;
    else
      mkdir -m 777 -p ${HOME}/miniconda/conda-bld;
      ./start_docker.sh ${HOME}/miniconda/conda-bld;
      alias CONDA_CMD="./conda_in_docker.sh";
      alias ANACONDA_CMD="docker exec psi_conda anaconda";
    fi
  - CONDA_CMD config --set always_yes yes --set changeps1 no
  - CONDA_CMD update -q --all
  - CONDA_CMD config --add channels defaults
  - CONDA_CMD install conda-build numpy anaconda-client
  # build
  - CONDA_CMD build -c $CONDA_CHANNEL --skip-existing brotli
  - '[[ "$TRAVIS_OS_NAME" != "linux" ]] || CONDA_CMD build -c $CONDA_CHANNEL --skip-existing readline'
  - CONDA_CMD build -c $CONDA_CHANNEL --skip-existing epics-base
  - CONDA_CMD build -c $CONDA_CHANNEL --skip-existing pyepics
  - CONDA_CMD build -c $CONDA_CHANNEL --skip-existing h5py
  - CONDA_CMD build -c $CONDA_CHANNEL --skip-existing lzf
  - CONDA_CMD build -c $CONDA_CHANNEL --skip-existing bottle
  - '[[ "$TRAVIS_OS_NAME" != "linux" ]] || CONDA_CMD build -c $CONDA_CHANNEL --skip-existing zeromq'
  - '[[ "$TRAVIS_OS_NAME" != "linux" ]] || CONDA_CMD build -c $CONDA_CHANNEL --skip-existing cx_oracle'

script:
  - echo "No test scripts to be run!"

deploy:
  provider: script
  script: find $HOME/miniconda/conda-bld/${TRAVIS_OS_NAME}-64 -name "*.tar.bz2" -exec ANACONDA_CMD -t $CONDA_TOKEN upload {} \;
