package:
    name: brotli
    version: 0.5.2

source:
    # path: ..
    git_rev: v0.5.2
    git_url: https://github.com/google/brotli.git

requirements:
    build:
        - python
    run:
        - python

about:
    home: https://github.com/google/brotli
    summary: "brotli library"
